In [211]:
import numpy as np
import matplotlib.pyplot as plt
from copy import deepcopy

In [212]:
class Sudoku:
    def __init__(self,initial_grid=None):
        self.sudoku     = self._initialize_sudoku(initial_grid)
        self.numberlist = self._initialize_numberlist()
        self.positions  = self._initialize_positions()
        self.solution   = np.zeros((9,9),dtype=int)

    def _initialize_sudoku(self,initial_grid):
        if initial_grid is None:
            return np.zeros((9,9),dtype=int)
        return initial_grid

    @staticmethod
    def _initialize_positions():
        return [(i,j) for i in range(0,9) for j in range(0,9)]

    @staticmethod
    def _initialize_numberlist():
        return np.array([1,2,3,4,5,6,7,8,9])

    def _is_possible(self,row,col,number):
        ## Checking column
        for i in range(0,9):
            if self.sudoku[i][col] == number:
                return False
        ## Checking row
        for i in range(0,9):
            if self.sudoku[row][i] == number:
                return False
        ## Checking square
        row_0, col_0 = (row//3) * 3, (col//3) * 3
        for i in range(0,3):
            for j in range(0,3):
                if self.sudoku[row_0 + i][col_0 + j] == number:
                    return False
        return True

    def _check_sudoku(self):
        for row in range(0 ,9):
            for col in range(0 ,9):
                if self.sudoku[row][col] == 0:
                    return False
        # We have a complete grid!
        return True

    def _permute_numberlist(self):
        self.numberlist = np.random.permutation(self.numberlist)

    def _permute_positions(self):
        self.positions = np.random.permutation(self.positions)

    def fill_sudoku(self):
        self._permute_numberlist()
        # Find next empty cell
        row, col = None, None
        for i in range(0, 81):
            row = i // 9
            col = i % 9
            if self.sudoku[row][col] == 0:
                for number in self.numberlist:
                    # Check that this value has not already be used
                   if self._is_possible(row,col,number):
                        self.sudoku[row][col]   = number
                        self.solution[row][col] = number
                        if self._check_sudoku():
                            return True
                        else:
                            if self.fill_sudoku():
                                return True
                break
        self.sudoku[row][col]   = 0
        self.solution[row][col] = 0

    def generate_unique_sudoku(self):
        currently_removed = None
        self._permute_positions()
        pos_nr = 0
        while pos_nr < 81:
            row,col               = self.positions[pos_nr]
            currently_removed     = self.sudoku[row][col]
            self.sudoku[row][col] = 0
            self._permute_numberlist()
            solution_counter = 0
            for number in self.numberlist:
                if self._is_possible(row,col,number):
                    solution_counter += 1
            if solution_counter > 1:
                self.sudoku[row][col] = currently_removed
                pos_nr += 1
            elif solution_counter == 1:
                pos_nr += 1
            elif solution_counter == 0:
                break

    def print_sudoku(self,grid = None):
        if grid is None: array = self.sudoku
        else: array = grid
        for row in range(array.shape[0]):
            if row % 3 == 0 and row != 0:
                print("- - - - - - - - - - -")
            for col in range(array.shape[1]):
                if col % 3 == 0 and col != 0:
                    print("| ", end = "")
                if col == 8:
                    print(array[row][col])
                else:
                    print(str(array[row][col]) + " ", end="")





In [213]:
my_sudoku = Sudoku()
my_sudoku.fill_sudoku()
my_sudoku.print_sudoku()

5 3 2 | 9 4 8 | 7 6 1
1 6 4 | 3 5 7 | 9 2 8
7 8 9 | 1 6 2 | 4 5 3
- - - - - - - - - - -
9 5 6 | 4 8 1 | 2 3 7
8 2 3 | 6 7 9 | 5 1 4
4 7 1 | 5 2 3 | 8 9 6
- - - - - - - - - - -
2 9 8 | 7 1 6 | 3 4 5
6 4 7 | 2 3 5 | 1 8 9
3 1 5 | 8 9 4 | 6 7 2


In [214]:
my_sudoku.generate_unique_sudoku()
my_sudoku.print_sudoku()

0 0 2 | 9 4 0 | 7 0 0
1 6 4 | 0 5 0 | 0 0 8
7 8 0 | 1 0 0 | 4 5 3
- - - - - - - - - - -
0 5 6 | 0 0 1 | 2 3 0
0 0 0 | 0 0 9 | 0 1 4
4 7 1 | 0 0 3 | 8 0 6
- - - - - - - - - - -
2 0 8 | 0 1 6 | 3 4 5
0 4 7 | 0 3 5 | 1 0 0
3 1 0 | 8 0 0 | 0 0 2


In [215]:
def check_sudoku(grid):
    for row in range(0 ,9):
        for col in range(0 ,9):
            if grid[row][col] == 0:
                return False
    # We have a complete grid!
    return True

def initialize_random_positions():
    return [(i,j) for i in range(0,9) for j in range(0,9)]

def is_possible(grid,row,col,number):
        ## Checking column
        for i in range(0,9):
            if grid[i][col] == number:
                return False
        ## Checking row
        for i in range(0,9):
            if grid[row][i] == number:
                return False
        ## Checking square
        row_0, col_0 = (row//3) * 3, (col//3) * 3
        for i in range(0,3):
            for j in range(0,3):
                if grid[row_0 + i][col_0 + j] == number:
                    return False
        return True



In [216]:
my_grid = deepcopy(my_sudoku.sudoku)
my_sudoku.print_sudoku()

0 0 2 | 9 4 0 | 7 0 0
1 6 4 | 0 5 0 | 0 0 8
7 8 0 | 1 0 0 | 4 5 3
- - - - - - - - - - -
0 5 6 | 0 0 1 | 2 3 0
0 0 0 | 0 0 9 | 0 1 4
4 7 1 | 0 0 3 | 8 0 6
- - - - - - - - - - -
2 0 8 | 0 1 6 | 3 4 5
0 4 7 | 0 3 5 | 1 0 0
3 1 0 | 8 0 0 | 0 0 2


In [217]:
def set_annotations(grid,annotation_tensor):
    number_list = [i for i in range(1,10)]
    for row_idx in range(9):
        for col_idx in range(9):
            if grid[row_idx][col_idx] == 0:
                for number in number_list:
                    if is_possible(grid,row_idx,col_idx,number):
                        annotation_tensor[row_idx][col_idx][number-1] = number


def update_annotations(row,col,number,annotation_tensor):
    # Update corresponding row of annotations
    for col_idx in range(0,9):
        if number in annotation_tensor[row][col_idx]:
            annotation_tensor[row][col_idx][number-1] = 0

    # Update corresponding col of annotations
    for row_idx in range(0,9):
        if number in annotation_tensor[row_idx][col]:
            annotation_tensor[row_idx][col][number-1] = 0

    # Update corresponding square of annotations
    row_0, col_0 = (row//3) * 3, (col//3) * 3
    for square_x in range(0,3):
        for square_y in range(0,3):
            if number in annotation_tensor[row_0+square_x][col_0+square_y]:
                annotation_tensor[row_0+square_x][col_0+square_y][number-1] = 0

    # Remove all annotations from entry (row,col) (this is where number is placed)
    for idx, val in enumerate(annotation_tensor[row][col]):
        if val != 0: annotation_tensor[row][col][idx] = 0

In [218]:
def naked_singles(grid,annotation_tensor) -> bool:
    succes = False
    for row_idx in range(annotation_tensor.shape[0]):
        for col_idx in range(annotation_tensor.shape[1]):
            # Only one annotation
            if np.count_nonzero(annotation_tensor[row_idx][col_idx]) == 1:
                # set value in grid
                grid[row_idx][col_idx] = int(np.nonzero(annotation_tensor[row_idx][col_idx])[0][0])
                # update annotation_tensor
                update_annotations(row_idx,col_idx,grid[row_idx][col_idx],annotation_tensor)
                succes = True
    return succes

def hidden_singles(grid,annotation_tensor) -> bool:
    succes = False
    occurence_counter = 0
    for number in range(1,10):

        # Checking rows
        occurence_counter = 0
        row_idx, col_idx = None, None
        for row in range(0,9):
            for col in range(0,9):
                if number in annotation_tensor[row][col]:
                    occurence_counter += 1
                    row_idx, col_idx = row, col
            if occurence_counter == 1:
                grid[row_idx][col_idx] = number
                update_annotations(row_idx,col_idx,grid[row_idx][col_idx],annotation_tensor)
                succes = True

        # Checking cols
        occurence_counter = 0
        row_idx, col_idx = None, None
        for col in range(0,9):
            for row in range(0,9):
                if number in annotation_tensor[row][col]:
                    occurence_counter += 1
                    row_idx, col_idx = row, col
            if occurence_counter == 1:
                grid[row_idx][col_idx] = number
                update_annotations(row_idx,col_idx,grid[row_idx][col_idx],annotation_tensor)
                succes = True

        # Checking square
        for square_x in range(0,3):
            for square_y in range(0,3):
                box_x,box_y = square_x*3,square_y*3

                occurence_counter = 0
                row_idx, col_idx  = None, None
                for i in range(0,3):
                    for j in range(0,3):
                        if number in annotation_tensor[box_x*3+i][box_y*3+j]:
                            occurence_counter += 1
                            row_idx, col_idx   = box_x*3+i, box_y*3+j
                if occurence_counter == 1:
                    grid[row_idx][col_idx] = number
                    update_annotations(row_idx,col_idx,grid[row_idx][col_idx],annotation_tensor)
                    succes = True
    return succes

In [219]:
def naked_pairs(annotation_tensor) -> bool:
    succes = False
    for row in range(0,9):
        for col in range(0,9):
            # First set of two annotations
            if np.count_nonzero(annotation_tensor[row][col]) == 2:
                pair = annotation_tensor[row][col][np.nonzero(annotation_tensor[row][col])[0]]
                # check against row
                for remaining_col in range(col,9):
                    # Second set of two annotations - now we have a pair!
                    if np.count_nonzero(annotation_tensor[row][remaining_col]) == 2:
                        if pair[0] in annotation_tensor[row][remaining_col] and pair[1] in annotation_tensor[row][remaining_col]:
                            # Checking all annotations in row for numbers in current pair
                            for i in range(0,9):
                                if (row,col) != (row,i) and (row, remaining_col) != (row,i):
                                    # Removing annotations
                                     annotation_tensor[row][i][pair[0]-1] = 0
                                     annotation_tensor[row][i][pair[1]-1] = 0
                                     succes = True
                # check against col
                for remaining_row in range(row,9):
                    # Second set of two annotations - now we have a pair!
                    if np.count_nonzero(annotation_tensor[remaining_row][col]) == 2:
                        if pair[0] in annotation_tensor[remaining_row][col] and pair[1] in annotation_tensor[remaining_row][col]:
                            # Checking all annotations in col for numbers in current pair
                            for i in range(0,9):
                                if (row,col) != (i,col) and (remaining_row, col) != (i,col):
                                    # Removing annotations
                                     annotation_tensor[i][col][pair[0]-1] = 0
                                     annotation_tensor[i][col][pair[1]-1] = 0
                                     succes = True

                # check against square
                row_0, col_0 = (row//3) * 3, (col//3) * 3
                for square_x in range(0,3):
                    for square_y in range(0,3):
                        # Second set of two annotations - now we have a pair!
                        if np.count_nonzero(annotation_tensor[row_0 + square_x][col_0 + square_y]) == 2:
                            if pair[0] in annotation_tensor[row_0 + square_x][col_0 + square_y] and pair[1] in annotation_tensor[row_0 + square_x][col_0 + square_y]:
                                # Checking all annotations in square for numbers in current pair
                                for i in range(0,3):
                                    for j in range(0,3):
                                        # only comparing w. instances of at least 2 annotations (therefore no checking against itself)
                                        if (row,col) != (row_0 + i,col_0 + j) and (row_0 + square_x,col_0 + square_y) != (row_0 + i,col_0 + j):
                                            # Removing annotations
                                            annotation_tensor[row_0 + i][col_0 + j][pair[0]-1] = 0
                                            annotation_tensor[row_0 + i][col_0 + j][pair[1]-1] = 0
                                            succes = True
    return succes

In [220]:
def uniqe_nonzero_pairs(annotation_list) -> np.ndarray:
    pairs = []
    for num1 in range(0,len(annotation_list)):
        if annotation_list[num1] != 0:
            for num2 in range(num1+1,len(annotation_list)):
                if annotation_list[num2] != 0:
                    pairs.append([annotation_list[num1],annotation_list[num2]])
    return np.array(pairs)

In [221]:
def hidden_pairs(annotation_tensor) -> bool:
    succes = False
    for col in range(0,9):
        for row in range(0,9):
            # Only checking when at least two annotations in first item of hidden-pair
            if np.count_nonzero(annotation_tensor[row][col]) >= 2:
                # All unique non-zero pairs in annotations of first item in hidden-pair
                current_pairs = uniqe_nonzero_pairs(annotation_tensor[row][col])
                for pair in current_pairs:
                    # check against row
                    for remaining_col in range(col,9):
                        # Candidate second item of hidden-pair
                        if np.count_nonzero(annotation_tensor[row][remaining_col]) >= 2:
                            if pair[0] in annotation_tensor[row][remaining_col] and pair[1] in annotation_tensor[row][remaining_col]:

                                # Assuring that hidden-pairs is unique (no other relevant occurrence of pair)
                                uniqueness_counter = 0

                                # Row
                                for i in range(0,9):
                                    # No checking against itself!
                                    if (row,i) != (row,col) and (row,i) != (row,remaining_col):
                                        if pair[0] in annotation_tensor[row][i] and pair[1] in annotation_tensor[row][i]:
                                            uniqueness_counter += 1

                                # Pair of annotations in hidden pair are is unique
                                if uniqueness_counter == 0:
                                    # Remove all other annotations from hidden pair
                                    annotation_tensor[row][remaining_col][(annotation_tensor[row][remaining_col] != pair[0]) & (annotation_tensor[row][remaining_col] !=pair[1])] = 0
                                    annotation_tensor[row][col][(annotation_tensor[row][col] != pair[0]) & (annotation_tensor[row][col] !=pair[1])]                               = 0
                                    succes = True

                    # check against col
                    for remaining_row in range(row,9):
                        # Candidate second item of hidden-pair
                        if np.count_nonzero(annotation_tensor[remaining_row][col]) >= 2:
                            if pair[0] in annotation_tensor[remaining_row][col] and pair[1] in annotation_tensor[remaining_row][col]:
                                # Assuring that hidden-pairs is unique (no other relevant occurrence of pair)
                                uniqueness_counter = 0

                                # Col
                                for i in range(0,9):
                                    # No checking against itself!
                                    if (i,col) != (row,col) and (i,col) != (remaining_row,col):
                                        if pair[0] in annotation_tensor[i][col] and pair[1] in annotation_tensor[i][col] :
                                            uniqueness_counter += 1

                                # Pair of annotations in hidden pair are is unique
                                if uniqueness_counter == 0:
                                    # Remove all other annotations from hidden pair
                                    annotation_tensor[remaining_row][col][(annotation_tensor[remaining_row][col] != pair[0]) & (annotation_tensor[remaining_row][col] !=pair[1])] = 0
                                    annotation_tensor[row][col][(annotation_tensor[row][col] != pair[0]) & (annotation_tensor[row][col] !=pair[1])]                               = 0
                                    succes = True

                    # check against square
                    row_0, col_0 = (row//3) * 3, (col//3) * 3
                    for i in range(0,3):
                        for j in range(0,3):
                            # Candidate second item of hidden-pair
                            if np.count_nonzero(annotation_tensor[row_0 + i][col_0 + j]) >= 2:
                                if pair[0] in annotation_tensor[row_0 + i][col_0 + j] and pair[1] in annotation_tensor[row_0 + i][col_0 + j]:
                                    # Assuring that hidden-pairs is unique (no other relevant occurrence of pair)
                                    uniqueness_counter = 0

                                    # Square
                                    for k in range(0,3):
                                        for l in range(0,3):
                                            # No checking against itself!
                                            if (row_0 + k,col_0 + l) != (row,col) and (row_0 + k,col_0 + l) != (row_0 + i,col_0 + j):
                                                if pair[0] in annotation_tensor[row_0 + k][col_0 + l] and pair[1] in annotation_tensor[row_0 + k][col_0 + l]:
                                                    uniqueness_counter += 1

                                    # Pair of annotations in hidden pair are is unique
                                    if uniqueness_counter == 0:
                                        # Remove all other annotations from hidden pair
                                        annotation_tensor[row_0 + i][col_0 + j][(annotation_tensor[row_0 + i][col_0 + j] != pair[0]) & (annotation_tensor[row_0 + i][col_0 + j]!=pair[1])] = 0
                                        annotation_tensor[row][col][(annotation_tensor[row][col] != pair[0]) & (annotation_tensor[row][col] !=pair[1])]                                    = 0
                                        succes = True
    return succes

In [222]:
def solvable(grid,annotation_tensor):

    if naked_singles(grid,annotation_tensor):
        if check_sudoku(grid):
            return True
        else:
            solvable(grid,annotation_tensor)

    elif hidden_singles(grid,annotation_tensor):
        if check_sudoku(grid):
            return True
        else:
            solvable(grid,annotation_tensor)

    elif naked_pairs(annotation_tensor):
        solvable(grid,annotation_tensor)

    elif hidden_pairs(annotation_tensor):
        solvable(grid,annotation_tensor)

    else:
        return False

In [223]:
def random_walk(grid) -> tuple:
    # Searches grid randomly for non-zero entry
    row, col = np.random.randint(0,9), np.random.randint(0,9)
    while grid[row][col] == 0:
        row, col = np.random.randint(0,9), np.random.randint(0,9)
    return row,col

In [224]:
my_grid = deepcopy(my_sudoku.solution)
print(my_grid)

[[5 3 2 9 4 8 7 6 1]
 [1 6 4 3 5 7 9 2 8]
 [7 8 9 1 6 2 4 5 3]
 [9 5 6 4 8 1 2 3 7]
 [8 2 3 6 7 9 5 1 4]
 [4 7 1 5 2 3 8 9 6]
 [2 9 8 7 1 6 3 4 5]
 [6 4 7 2 3 5 1 8 9]
 [3 1 5 8 9 4 6 7 2]]


In [225]:
def set_sudoku(grid,nr_of_holes):
    annotation_tensor = np.zeros((9,9,9),dtype = int)
    set_annotations(grid,annotation_tensor)
    nr_current_holes = 0
    zero_positions = []
    # Main loop
    while nr_current_holes < nr_of_holes:
        for position in zero_positions:
            grid[position[0]][position[1]] = 0
        row, col = random_walk(grid)
        if solvable(grid,annotation_tensor):
            nr_current_holes += 1
            zero_positions.append([row,col])
    # Final update
    for positions in zero_positions:
        grid[positions[0]][positions[1]] = 0


In [226]:
set_sudoku(my_grid,2)

IndexError: index 9 is out of bounds for axis 0 with size 9